# Generated by Django 4.2.19 on 2025-03-30 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecycleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('original_path', models.CharField(max_length=255)),
                ('size', models.IntegerField()),
                ('delete_time', models.DateTimeField(auto_now_add=True)),
                ('remaining_days', models.IntegerField()),
            ],
        ),
    ]
