# Generated by Django 4.2.19 on 2025-02-26 13:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file_path', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('thumbnail_path', models.ImageField(blank=True, upload_to='thumbnails/%Y/%m/%d/')),
                ('upload_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('taken_time', models.DateTimeField(blank=True, null=True)),
                ('size', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('format', models.CharField(max_length=10)),
                ('albums', models.ManyToManyField(related_name='photos', to='photos.album')),
                ('tags', models.ManyToManyField(related_name='photos', to='photos.tag')),
            ],
            options={
                'ordering': ['-upload_time'],
            },
        ),
    ]
