# Generated by Django 4.2.19 on 2025-03-22 10:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20250316_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='taken_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
