# Generated by Django 4.2.19 on 2025-08-14 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_alter_photo_taken_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='字段键名', max_length=100)),
                ('name', models.CharField(help_text='字段显示名称', max_length=200)),
                ('value', models.TextField(help_text='字段值')),
                ('field_type', models.CharField(choices=[('text', '文本'), ('number', '数字'), ('date', '日期'), ('boolean', '布尔值'), ('json', 'JSON数据')], default='text', max_length=20)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_metadata', to='photos.photo')),
            ],
            options={
                'ordering': ['created_time'],
                'unique_together': {('photo', 'key')},
            },
        ),
    ]
